export const database = [
  {
    id: 1,
    name: "Casque Audio Sans Fil Premium",
    imageUrl: "/image/header-scroll2.png",
    discountPercentage: 20,
    originalPrice: 199.99,
    discountedPrice: 159.99,
    rating: 4,
  },
  {
    id: 2,
    name: "Smartphone Haut de Gamme 128GB",
    imageUrl: "/image/header-scroll3.png",
    discountPercentage: 15,
    originalPrice: 899.99,
    discountedPrice: 764.99,
    rating: 5,
  },
  {
    id: 3,
    name: "Montre Connectée Étanche",
    imageUrl: "/image/header-scroll4.png",
    discountPercentage: 30,
    originalPrice: 249.99,
    discountedPrice: 174.99,
    rating: 3,
  },
  {
    id: 4,
    name: "Enceinte Bluetooth Portable",
    imageUrl: "/image/header-scroll5.png",
    discountPercentage: 25,
    originalPrice: 129.99,
    discountedPrice: 97.49,
    rating: 4,
  },
  {
    id: 5,
    name: "Clavier Mécanique RGB",
    imageUrl: "/image/explorer1.png",
    discountPercentage: 10,
    originalPrice: 89.99,
    discountedPrice: 80.99,
    rating: 5,
  },
  {
    id: 6,
    name: "Souris Gaming Haute Précision",
    imageUrl: "/image/explorer2.png",
    discountPercentage: 40,
    originalPrice: 59.99,
    discountedPrice: 35.99,
    rating: 4,
  },
  {
    id: 1,
    name: "Casque Audio Sans Fil Premium",
    imageUrl: "/image/explorer1.png",
    discountPercentage: 20,
    originalPrice: 199.99,
    discountedPrice: 159.99,
    rating: 4,
  },
  {
    id: 2,
    name: "Smartphone Haut de Gamme 128GB",
    imageUrl: "/image/explorer2.png",
    discountPercentage: 15,
    originalPrice: 899.99,
    discountedPrice: 764.99,
    rating: 5,
  },
  {
    id: 3,
    name: "Montre Connectée Étanche",
    imageUrl: "/image/explorer3.png",
    discountPercentage: 30,
    originalPrice: 249.99,
    discountedPrice: 174.99,
    rating: 3,
  },
  {
    id: 4,
    name: "Enceinte Bluetooth Portable",
    imageUrl: "/image/explore4.png",
    discountPercentage: 25,
    originalPrice: 129.99,
    discountedPrice: 97.49,
    rating: 4,
  },
  {
    id: 5,
    name: "Clavier Mécanique RGB",
    imageUrl: "/image/explore6.png",
    discountPercentage: 10,
    originalPrice: 89.99,
    discountedPrice: 80.99,
    rating: 5,
  },
  {
    id: 6,
    name: "Souris Gaming Haute Précision",
    imageUrl: "/image/explore7.png",
    discountPercentage: 40,
    originalPrice: 59.99,
    discountedPrice: 35.99,
    rating: 4,
  },
  {
    id: 1,
    name: "Casque Audio Sans Fil Premium",
    imageUrl: "/image/explorer1.png",
    discountPercentage: 20,
    originalPrice: 199.99,
    discountedPrice: 159.99,
    rating: 4,
  },
  {
    id: 2,
    name: "Smartphone Haut de Gamme 128GB",
    imageUrl: "/image/explorer2.png",
    discountPercentage: 15,
    originalPrice: 899.99,
    discountedPrice: 764.99,
    rating: 5,
  },
  {
    id: 3,
    name: "Montre Connectée Étanche",
    imageUrl: "/image/explorer3.png",
    discountPercentage: 30,
    originalPrice: 249.99,
    discountedPrice: 174.99,
    rating: 3,
  },
  {
    id: 4,
    name: "Enceinte Bluetooth Portable",
    imageUrl: "/image/explore4.png",
    discountPercentage: 25,
    originalPrice: 129.99,
    discountedPrice: 97.49,
    rating: 4,
  },
  {
    id: 5,
    name: "Clavier Mécanique RGB",
    imageUrl: "/image/explore6.png",
    discountPercentage: 10,
    originalPrice: 89.99,
    discountedPrice: 80.99,
    rating: 5,
  },
  {
    id: 6,
    name: "Souris Gaming Haute Précision",
    imageUrl: "/image/explore7.png",
    discountPercentage: 40,
    originalPrice: 59.99,
    discountedPrice: 35.99,
    rating: 4,
  },
  {
    id: 1,
    name: "Casque Audio Sans Fil Premium",
    imageUrl: "/image/explorer1.png",
    discountPercentage: 20,
    originalPrice: 199.99,
    discountedPrice: 159.99,
    rating: 4,
  },
  {
    id: 2,
    name: "Smartphone Haut de Gamme 128GB",
    imageUrl: "/image/explorer2.png",
    discountPercentage: 15,
    originalPrice: 899.99,
    discountedPrice: 764.99,
    rating: 5,
  },
  {
    id: 3,
    name: "Montre Connectée Étanche",
    imageUrl: "/image/explorer3.png",
    discountPercentage: 30,
    originalPrice: 249.99,
    discountedPrice: 174.99,
    rating: 3,
  },
  {
    id: 4,
    name: "Enceinte Bluetooth Portable",
    imageUrl: "/image/explore4.png",
    discountPercentage: 25,
    originalPrice: 129.99,
    discountedPrice: 97.49,
    rating: 4,
  },
  {
    id: 5,
    name: "Clavier Mécanique RGB",
    imageUrl: "/image/explore6.png",
    discountPercentage: 10,
    originalPrice: 89.99,
    discountedPrice: 80.99,
    rating: 5,
  },
  {
    id: 6,
    name: "Souris Gaming Haute Précision",
    imageUrl: "/image/explore7.png",
    discountPercentage: 40,
    originalPrice: 59.99,
    discountedPrice: 35.99,
    rating: 4,
  },
];
